version: "3.9"

services:
  app:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - NO_SSL_VERIFY=${NO_SSL_VERIFY}
    depends_on:
      - "db"
    restart: always
  db:
    image: postgres:14
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    expose:
      - "5432"
      